{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "smart-fhir.fullname" . }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts.host }}
      http:
        paths:
{{ toYaml .Values.ingress.hosts.paths | indent 8 }}
{{- end -}}
